name: Simulate IoT Data

on:
  schedule:
    # Runs every hour at the start of the hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Call simulation endpoint
        run: |
          curl -X GET https://infrasight.aseck.dev/api/v2/cron/simulate \
            -H "Content-Type: application/json" \
            -f || echo "Request failed"
